package com.siu.android.athismons.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CARD.
 */
public class Card implements java.io.Serializable {

    private Long id;
    private String title;
    private String building;
    private String street;
    private String city;
    private String postalCode;
    private String addressComplement;
    private String picture;
    private String contact;
    private String website;
    private String email;
    private String phone1;
    private String phone2;
    private String listPicture;
    private Double latitude;
    private Double longitude;
    private long directoryId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, String title, String building, String street, String city, String postalCode, String addressComplement, String picture, String contact, String website, String email, String phone1, String phone2, String listPicture, Double latitude, Double longitude, long directoryId) {
        this.id = id;
        this.title = title;
        this.building = building;
        this.street = street;
        this.city = city;
        this.postalCode = postalCode;
        this.addressComplement = addressComplement;
        this.picture = picture;
        this.contact = contact;
        this.website = website;
        this.email = email;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.listPicture = listPicture;
        this.latitude = latitude;
        this.longitude = longitude;
        this.directoryId = directoryId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBuilding() {
        return building;
    }

    public void setBuilding(String building) {
        this.building = building;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getAddressComplement() {
        return addressComplement;
    }

    public void setAddressComplement(String addressComplement) {
        this.addressComplement = addressComplement;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone1() {
        return phone1;
    }

    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    public String getPhone2() {
        return phone2;
    }

    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getListPicture() {
        return listPicture;
    }

    public void setListPicture(String listPicture) {
        this.listPicture = listPicture;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public long getDirectoryId() {
        return directoryId;
    }

    public void setDirectoryId(long directoryId) {
        this.directoryId = directoryId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
