package com.siu.android.athismons.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.siu.android.athismons.model.Detail;
// KEEP INCLUDES END
/**
 * Entity mapped to table MENU.
 */
public class Menu implements java.io.Serializable, com.siu.android.athismons.model.Detail {

    private Long id;
    private String title;
    private String description;
    private String link;
    private String picture;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Menu() {
    }

    public Menu(Long id) {
        this.id = id;
    }

    public Menu(Long id, String title, String description, String link, String picture) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.link = link;
        this.picture = picture;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String getUrl() {
        return link;
    }

    @Override
    public String getContent() {
        return description;
    }
    // KEEP METHODS END

}
